"""drop the bank tables' foreign keys

Revision ID: ebebdad3d551
Revises: 978a1882a871
Create Date: 2026-10-04 03:28:49.845566

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ebebdad3d551"
down_revision: str | Sequence[str] | None = "978a1882a871"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("bank_accounts_client_id_fkey"), "bank_accounts", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("bank_clients_primary_rm_id_fkey"), "bank_clients", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("bank_research_analyst_id_fkey"), "bank_research", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("bank_trades_client_id_fkey"), "bank_trades", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("bank_trades_trader_id_fkey"), "bank_trades", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("bank_trades_account_id_fkey"), "bank_trades", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("bank_transactions_account_id_fkey"),
        "bank_transactions",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("bank_transactions_client_id_fkey"),
        "bank_transactions",
        type_="foreignkey",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("bank_transactions_client_id_fkey"),
        "bank_transactions",
        "bank_clients",
        ["client_id"],
        ["client_id"],
    )
    op.create_foreign_key(
        op.f("bank_transactions_account_id_fkey"),
        "bank_transactions",
        "bank_accounts",
        ["account_id"],
        ["account_id"],
    )
    op.create_foreign_key(
        op.f("bank_trades_account_id_fkey"),
        "bank_trades",
        "bank_accounts",
        ["account_id"],
        ["account_id"],
    )
    op.create_foreign_key(
        op.f("bank_trades_trader_id_fkey"),
        "bank_trades",
        "users",
        ["trader_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("bank_trades_client_id_fkey"),
        "bank_trades",
        "bank_clients",
        ["client_id"],
        ["client_id"],
    )
    op.create_foreign_key(
        op.f("bank_research_analyst_id_fkey"),
        "bank_research",
        "users",
        ["analyst_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("bank_clients_primary_rm_id_fkey"),
        "bank_clients",
        "users",
        ["primary_rm_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("bank_accounts_client_id_fkey"),
        "bank_accounts",
        "bank_clients",
        ["client_id"],
        ["client_id"],
    )
    # ### end Alembic commands ###
