"""add the provisioning log

Revision ID: 66da6ae3207b
Revises: b83da9ec395a
Create Date: 2026-10-03 21:40:18.984669

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "66da6ae3207b"
down_revision: str | Sequence[str] | None = "b83da9ec395a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "directory_events",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name="directory_events_org_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="directory_events_user_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_directory_events_created_at"),
        "directory_events",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_directory_events_org_id"), "directory_events", ["org_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_directory_events_org_id"), table_name="directory_events")
    op.drop_index(op.f("ix_directory_events_created_at"), table_name="directory_events")
    op.drop_table("directory_events")
    # ### end Alembic commands ###
