"""drop the bank tables to key them by organization

Revision ID: 74f22d5dbfcb
Revises: ebebdad3d551
Create Date: 2026-10-04 03:29:04.395797

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "74f22d5dbfcb"
down_revision: str | Sequence[str] | None = "ebebdad3d551"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bank_accounts_client_id"), table_name="bank_accounts")
    op.drop_table("bank_accounts")
    op.drop_index(op.f("ix_bank_trades_account_id"), table_name="bank_trades")
    op.drop_index(op.f("ix_bank_trades_client_id"), table_name="bank_trades")
    op.drop_table("bank_trades")
    op.drop_index(op.f("ix_bank_clients_client_name"), table_name="bank_clients")
    op.drop_table("bank_clients")
    op.drop_index(op.f("ix_bank_research_coverage_symbol"), table_name="bank_research")
    op.drop_table("bank_research")
    op.drop_table("bank_identity_profiles")
    op.drop_table("bank_data_catalog")
    op.drop_index(
        op.f("ix_bank_transactions_account_id"), table_name="bank_transactions"
    )
    op.drop_index(
        op.f("ix_bank_transactions_client_id"), table_name="bank_transactions"
    )
    op.drop_table("bank_transactions")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bank_transactions",
        sa.Column("transaction_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("client_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("account_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "transaction_type", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "amount_usd",
            sa.NUMERIC(precision=18, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("currency", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "timestamp", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("origin_country", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "destination_country", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "beneficiary_name", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "beneficiary_account", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column("purpose", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("channel", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("aml_risk_score", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("fraud_score", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("alert_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "investigation_notes", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column("source_system", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("transaction_id", name=op.f("bank_transactions_pkey")),
    )
    op.create_index(
        op.f("ix_bank_transactions_client_id"),
        "bank_transactions",
        ["client_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bank_transactions_account_id"),
        "bank_transactions",
        ["account_id"],
        unique=False,
    )
    op.create_table(
        "bank_data_catalog",
        sa.Column("table_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("field_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("sensitivity", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("rationale", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint(
            "table_name", "field_name", name=op.f("bank_data_catalog_pkey")
        ),
    )
    op.create_table(
        "bank_identity_profiles",
        sa.Column("identity", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("display_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("permission", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("identity", name=op.f("bank_identity_profiles_pkey")),
    )
    op.create_table(
        "bank_research",
        sa.Column("research_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("research_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("asset_class", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("sector", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("coverage_symbol", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("analyst_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("publication_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("audience", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("rating", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "target_price",
            sa.NUMERIC(precision=18, scale=4),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("embargo_until", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column(
            "client_access_tier", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column("summary", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "internal_draft_notes", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column("source_model", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("watermark", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("research_id", name=op.f("bank_research_pkey")),
    )
    op.create_index(
        op.f("ix_bank_research_coverage_symbol"),
        "bank_research",
        ["coverage_symbol"],
        unique=False,
    )
    op.create_table(
        "bank_clients",
        sa.Column("client_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("client_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("client_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("country", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("country_code", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("city", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("sector", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "relationship_division", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "relationship_tier", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "onboarding_status", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column("risk_rating", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("kyc_status", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "sanctions_screening", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column("primary_rm_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "aum_usd_mn",
            sa.NUMERIC(precision=18, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "credit_limit_usd_mn",
            sa.NUMERIC(precision=18, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "annual_revenue_usd_mn",
            sa.NUMERIC(precision=18, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("tax_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("legal_address", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("contact_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("contact_email", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("contact_phone", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "beneficial_owner", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column("internal_notes", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("client_id", name=op.f("bank_clients_pkey")),
    )
    op.create_index(
        op.f("ix_bank_clients_client_name"),
        "bank_clients",
        ["client_name"],
        unique=False,
    )
    op.create_table(
        "bank_trades",
        sa.Column("trade_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("client_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("account_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("desk", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("asset_class", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("instrument", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("side", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("quantity", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "price",
            sa.NUMERIC(precision=18, scale=6),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "notional_usd",
            sa.NUMERIC(precision=18, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("currency", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "trade_timestamp",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("settlement_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("trader_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("venue", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "pnl_usd",
            sa.NUMERIC(precision=18, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "var_1d_usd",
            sa.NUMERIC(precision=18, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("strategy", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("counterparty", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("internal_comment", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("trade_id", name=op.f("bank_trades_pkey")),
    )
    op.create_index(
        op.f("ix_bank_trades_client_id"), "bank_trades", ["client_id"], unique=False
    )
    op.create_index(
        op.f("ix_bank_trades_account_id"), "bank_trades", ["account_id"], unique=False
    )
    op.create_table(
        "bank_accounts",
        sa.Column("account_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("client_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("account_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("currency", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("jurisdiction", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("opening_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "cash_balance_usd",
            sa.NUMERIC(precision=18, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "credit_exposure_usd",
            sa.NUMERIC(precision=18, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "margin_requirement_usd",
            sa.NUMERIC(precision=18, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "portfolio_value_usd",
            sa.NUMERIC(precision=18, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("internal_rating", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("account_number", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("swift_bic", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "iban_or_local_account", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "authorized_signatory", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "restriction_flag", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("account_id", name=op.f("bank_accounts_pkey")),
    )
    op.create_index(
        op.f("ix_bank_accounts_client_id"), "bank_accounts", ["client_id"], unique=False
    )
    # ### end Alembic commands ###
