"""add golden socks bank tables

Revision ID: 9541ef184c5d
Revises: d9468defef33
Create Date: 2026-10-03 13:41:09.114473

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9541ef184c5d"
down_revision: str | Sequence[str] | None = "d9468defef33"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bank_data_catalog",
        sa.Column("table_name", sa.String(), nullable=False),
        sa.Column("field_name", sa.String(), nullable=False),
        sa.Column("sensitivity", sa.String(), nullable=False),
        sa.Column("rationale", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("table_name", "field_name"),
    )
    op.create_table(
        "bank_employees",
        sa.Column("employee_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("division", sa.String(), nullable=False),
        sa.Column("desk_or_team", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("office", sa.String(), nullable=False),
        sa.Column("manager_id", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=False),
        sa.Column("cost_center", sa.String(), nullable=False),
        sa.Column("clearance_level", sa.String(), nullable=False),
        sa.Column("employment_status", sa.String(), nullable=False),
        sa.Column("salary_band", sa.String(), nullable=False),
        sa.Column("base_salary_usd", sa.Integer(), nullable=False),
        sa.Column("bonus_usd", sa.Integer(), nullable=False),
        sa.Column("home_address", sa.String(), nullable=False),
        sa.Column("national_id_demo", sa.String(), nullable=False),
        sa.Column("device_id", sa.String(), nullable=False),
        sa.Column("privileged_access", sa.Boolean(), nullable=False),
        sa.Column("api_token_demo", sa.String(), nullable=False),
        sa.Column("performance_rating", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["manager_id"],
            ["bank_employees.employee_id"],
        ),
        sa.PrimaryKeyConstraint("employee_id"),
    )
    op.create_table(
        "bank_identity_profiles",
        sa.Column("identity", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("permission", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("identity"),
    )
    op.create_table(
        "bank_clients",
        sa.Column("client_id", sa.String(), nullable=False),
        sa.Column("client_name", sa.String(), nullable=False),
        sa.Column("client_type", sa.String(), nullable=False),
        sa.Column("country", sa.String(), nullable=False),
        sa.Column("country_code", sa.String(), nullable=False),
        sa.Column("city", sa.String(), nullable=False),
        sa.Column("sector", sa.String(), nullable=False),
        sa.Column("relationship_division", sa.String(), nullable=False),
        sa.Column("relationship_tier", sa.String(), nullable=False),
        sa.Column("onboarding_status", sa.String(), nullable=False),
        sa.Column("risk_rating", sa.String(), nullable=False),
        sa.Column("kyc_status", sa.String(), nullable=False),
        sa.Column("sanctions_screening", sa.String(), nullable=False),
        sa.Column("primary_rm_id", sa.String(), nullable=False),
        sa.Column("aum_usd_mn", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column(
            "credit_limit_usd_mn", sa.Numeric(precision=18, scale=2), nullable=False
        ),
        sa.Column(
            "annual_revenue_usd_mn", sa.Numeric(precision=18, scale=2), nullable=False
        ),
        sa.Column("tax_id_demo", sa.String(), nullable=False),
        sa.Column("legal_address", sa.String(), nullable=False),
        sa.Column("contact_name", sa.String(), nullable=False),
        sa.Column("contact_email", sa.String(), nullable=False),
        sa.Column("contact_phone", sa.String(), nullable=False),
        sa.Column("beneficial_owner", sa.String(), nullable=False),
        sa.Column("internal_notes", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["primary_rm_id"],
            ["bank_employees.employee_id"],
        ),
        sa.PrimaryKeyConstraint("client_id"),
    )
    op.create_index(
        op.f("ix_bank_clients_client_name"),
        "bank_clients",
        ["client_name"],
        unique=False,
    )
    op.create_table(
        "bank_research",
        sa.Column("research_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("research_type", sa.String(), nullable=False),
        sa.Column("asset_class", sa.String(), nullable=False),
        sa.Column("sector", sa.String(), nullable=False),
        sa.Column("coverage_symbol", sa.String(), nullable=False),
        sa.Column("analyst_id", sa.String(), nullable=False),
        sa.Column("publication_date", sa.Date(), nullable=False),
        sa.Column("audience", sa.String(), nullable=False),
        sa.Column("rating", sa.String(), nullable=False),
        sa.Column(
            "target_price_demo", sa.Numeric(precision=18, scale=4), nullable=True
        ),
        sa.Column("embargo_until", sa.Date(), nullable=False),
        sa.Column("client_access_tier", sa.String(), nullable=False),
        sa.Column("summary", sa.String(), nullable=False),
        sa.Column("internal_draft_notes", sa.String(), nullable=True),
        sa.Column("source_model", sa.String(), nullable=False),
        sa.Column("canary_token_demo", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analyst_id"],
            ["bank_employees.employee_id"],
        ),
        sa.PrimaryKeyConstraint("research_id"),
    )
    op.create_index(
        op.f("ix_bank_research_coverage_symbol"),
        "bank_research",
        ["coverage_symbol"],
        unique=False,
    )
    op.create_table(
        "bank_accounts",
        sa.Column("account_id", sa.String(), nullable=False),
        sa.Column("client_id", sa.String(), nullable=False),
        sa.Column("account_type", sa.String(), nullable=False),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column("jurisdiction", sa.String(), nullable=False),
        sa.Column("opening_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "cash_balance_usd", sa.Numeric(precision=18, scale=2), nullable=False
        ),
        sa.Column(
            "credit_exposure_usd", sa.Numeric(precision=18, scale=2), nullable=False
        ),
        sa.Column(
            "margin_requirement_usd", sa.Numeric(precision=18, scale=2), nullable=False
        ),
        sa.Column(
            "portfolio_value_usd", sa.Numeric(precision=18, scale=2), nullable=False
        ),
        sa.Column("internal_rating", sa.String(), nullable=False),
        sa.Column("account_number_demo", sa.String(), nullable=False),
        sa.Column("swift_bic_demo", sa.String(), nullable=False),
        sa.Column("iban_or_local_account_demo", sa.String(), nullable=False),
        sa.Column("authorized_signatory", sa.String(), nullable=False),
        sa.Column("restriction_flag", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["bank_clients.client_id"],
        ),
        sa.PrimaryKeyConstraint("account_id"),
    )
    op.create_index(
        op.f("ix_bank_accounts_client_id"), "bank_accounts", ["client_id"], unique=False
    )
    op.create_table(
        "bank_trades",
        sa.Column("trade_id", sa.String(), nullable=False),
        sa.Column("client_id", sa.String(), nullable=False),
        sa.Column("account_id", sa.String(), nullable=False),
        sa.Column("desk", sa.String(), nullable=False),
        sa.Column("asset_class", sa.String(), nullable=False),
        sa.Column("instrument", sa.String(), nullable=False),
        sa.Column("side", sa.String(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("price_demo", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("notional_usd", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column("trade_timestamp", sa.DateTime(), nullable=False),
        sa.Column("settlement_date", sa.Date(), nullable=False),
        sa.Column("trader_id", sa.String(), nullable=False),
        sa.Column("venue", sa.String(), nullable=False),
        sa.Column("pnl_usd", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("var_1d_usd", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("strategy", sa.String(), nullable=False),
        sa.Column("counterparty_demo", sa.String(), nullable=False),
        sa.Column("internal_comment", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["bank_accounts.account_id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["bank_clients.client_id"],
        ),
        sa.ForeignKeyConstraint(
            ["trader_id"],
            ["bank_employees.employee_id"],
        ),
        sa.PrimaryKeyConstraint("trade_id"),
    )
    op.create_index(
        op.f("ix_bank_trades_account_id"), "bank_trades", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_bank_trades_client_id"), "bank_trades", ["client_id"], unique=False
    )
    op.create_table(
        "bank_transactions",
        sa.Column("transaction_id", sa.String(), nullable=False),
        sa.Column("client_id", sa.String(), nullable=False),
        sa.Column("account_id", sa.String(), nullable=False),
        sa.Column("transaction_type", sa.String(), nullable=False),
        sa.Column("amount_usd", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("origin_country", sa.String(), nullable=False),
        sa.Column("destination_country", sa.String(), nullable=False),
        sa.Column("beneficiary_name", sa.String(), nullable=False),
        sa.Column("beneficiary_account_demo", sa.String(), nullable=False),
        sa.Column("purpose", sa.String(), nullable=False),
        sa.Column("channel", sa.String(), nullable=False),
        sa.Column("aml_risk_score", sa.Integer(), nullable=False),
        sa.Column("fraud_score", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("alert_id", sa.String(), nullable=True),
        sa.Column("investigation_notes", sa.String(), nullable=True),
        sa.Column("source_system", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["bank_accounts.account_id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["bank_clients.client_id"],
        ),
        sa.PrimaryKeyConstraint("transaction_id"),
    )
    op.create_index(
        op.f("ix_bank_transactions_account_id"),
        "bank_transactions",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bank_transactions_client_id"),
        "bank_transactions",
        ["client_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_bank_transactions_client_id"), table_name="bank_transactions"
    )
    op.drop_index(
        op.f("ix_bank_transactions_account_id"), table_name="bank_transactions"
    )
    op.drop_table("bank_transactions")
    op.drop_index(op.f("ix_bank_trades_client_id"), table_name="bank_trades")
    op.drop_index(op.f("ix_bank_trades_account_id"), table_name="bank_trades")
    op.drop_table("bank_trades")
    op.drop_index(op.f("ix_bank_accounts_client_id"), table_name="bank_accounts")
    op.drop_table("bank_accounts")
    op.drop_index(op.f("ix_bank_research_coverage_symbol"), table_name="bank_research")
    op.drop_table("bank_research")
    op.drop_index(op.f("ix_bank_clients_client_name"), table_name="bank_clients")
    op.drop_table("bank_clients")
    op.drop_table("bank_identity_profiles")
    op.drop_table("bank_employees")
    op.drop_table("bank_data_catalog")
    # ### end Alembic commands ###
