"""add SCIM directory sync of users and groups

Revision ID: b83da9ec395a
Revises: e1e73d883363
Create Date: 2026-10-03 20:58:05.356515

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b83da9ec395a"
down_revision: str | Sequence[str] | None = "e1e73d883363"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "directory_groups",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name="directory_groups_org_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "org_id", "display_name", name="directory_groups_org_id_display_name_key"
        ),
    )
    op.create_index(
        op.f("ix_directory_groups_org_id"), "directory_groups", ["org_id"], unique=False
    )
    op.create_table(
        "directory_group_members",
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["directory_groups.id"],
            name="directory_group_members_group_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="directory_group_members_user_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("group_id", "user_id"),
    )
    op.create_index(
        op.f("ix_directory_group_members_user_id"),
        "directory_group_members",
        ["user_id"],
        unique=False,
    )
    op.add_column(
        "organizations",
        sa.Column("scim_token_hash", sa.String(length=64), nullable=True),
    )
    op.create_index(
        op.f("ix_organizations_scim_token_hash"),
        "organizations",
        ["scim_token_hash"],
        unique=True,
    )
    op.add_column(
        "users", sa.Column("external_id", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "users",
        sa.Column(
            "active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "active")
    op.drop_column("users", "external_id")
    op.drop_index(op.f("ix_organizations_scim_token_hash"), table_name="organizations")
    op.drop_column("organizations", "scim_token_hash")
    op.drop_index(
        op.f("ix_directory_group_members_user_id"), table_name="directory_group_members"
    )
    op.drop_table("directory_group_members")
    op.drop_index(op.f("ix_directory_groups_org_id"), table_name="directory_groups")
    op.drop_table("directory_groups")
    # ### end Alembic commands ###
