"""pin MCP tool definitions

Revision ID: 7ba17aeafda5
Revises: 66da6ae3207b
Create Date: 2026-10-03 22:26:56.306015

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7ba17aeafda5"
down_revision: str | Sequence[str] | None = "66da6ae3207b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mcp_servers",
        sa.Column(
            "tool_pins",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mcp_servers", "tool_pins")
    # ### end Alembic commands ###
