"""pin MCP tool definitions

Revision ID: c72b4aa7bdd2
Revises: b83da9ec395a
Create Date: 2026-10-03 21:59:59.383730

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c72b4aa7bdd2"
down_revision: str | Sequence[str] | None = "b83da9ec395a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mcp_servers",
        sa.Column(
            "tool_pins",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mcp_servers", "tool_pins")
    # ### end Alembic commands ###
