"""create the bank tables keyed by organization, and demo sandboxes

Revision ID: 5cb7bbd8e756
Revises: 74f22d5dbfcb
Create Date: 2026-10-04 03:41:27.379316

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5cb7bbd8e756"
down_revision: str | Sequence[str] | None = "74f22d5dbfcb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bank_accounts",
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.String(), nullable=False),
        sa.Column("client_id", sa.String(), nullable=False),
        sa.Column("account_type", sa.String(), nullable=False),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column("jurisdiction", sa.String(), nullable=False),
        sa.Column("opening_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "cash_balance_usd", sa.Numeric(precision=18, scale=2), nullable=False
        ),
        sa.Column(
            "credit_exposure_usd", sa.Numeric(precision=18, scale=2), nullable=False
        ),
        sa.Column(
            "margin_requirement_usd", sa.Numeric(precision=18, scale=2), nullable=False
        ),
        sa.Column(
            "portfolio_value_usd", sa.Numeric(precision=18, scale=2), nullable=False
        ),
        sa.Column("internal_rating", sa.String(), nullable=False),
        sa.Column("account_number", sa.String(), nullable=False),
        sa.Column("swift_bic", sa.String(), nullable=False),
        sa.Column("iban_or_local_account", sa.String(), nullable=False),
        sa.Column("authorized_signatory", sa.String(), nullable=False),
        sa.Column("restriction_flag", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("org_id", "account_id"),
    )
    op.create_index(
        "ix_bank_accounts_org_id_client_id",
        "bank_accounts",
        ["org_id", "client_id"],
        unique=False,
    )
    op.create_table(
        "bank_clients",
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("client_id", sa.String(), nullable=False),
        sa.Column("client_name", sa.String(), nullable=False),
        sa.Column("client_type", sa.String(), nullable=False),
        sa.Column("country", sa.String(), nullable=False),
        sa.Column("country_code", sa.String(), nullable=False),
        sa.Column("city", sa.String(), nullable=False),
        sa.Column("sector", sa.String(), nullable=False),
        sa.Column("relationship_division", sa.String(), nullable=False),
        sa.Column("relationship_tier", sa.String(), nullable=False),
        sa.Column("onboarding_status", sa.String(), nullable=False),
        sa.Column("risk_rating", sa.String(), nullable=False),
        sa.Column("kyc_status", sa.String(), nullable=False),
        sa.Column("sanctions_screening", sa.String(), nullable=False),
        sa.Column("primary_rm_id", sa.Uuid(), nullable=False),
        sa.Column("aum_usd_mn", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column(
            "credit_limit_usd_mn", sa.Numeric(precision=18, scale=2), nullable=False
        ),
        sa.Column(
            "annual_revenue_usd_mn", sa.Numeric(precision=18, scale=2), nullable=False
        ),
        sa.Column("tax_id", sa.String(), nullable=False),
        sa.Column("legal_address", sa.String(), nullable=False),
        sa.Column("contact_name", sa.String(), nullable=False),
        sa.Column("contact_email", sa.String(), nullable=False),
        sa.Column("contact_phone", sa.String(), nullable=False),
        sa.Column("beneficial_owner", sa.String(), nullable=False),
        sa.Column("internal_notes", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("org_id", "client_id"),
    )
    op.create_index(
        "ix_bank_clients_org_id_client_name",
        "bank_clients",
        ["org_id", "client_name"],
        unique=False,
    )
    op.create_table(
        "bank_data_catalog",
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("table_name", sa.String(), nullable=False),
        sa.Column("field_name", sa.String(), nullable=False),
        sa.Column("sensitivity", sa.String(), nullable=False),
        sa.Column("rationale", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("org_id", "table_name", "field_name"),
    )
    op.create_table(
        "bank_identity_profiles",
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("identity", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("permission", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("org_id", "identity"),
    )
    op.create_table(
        "bank_research",
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("research_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("research_type", sa.String(), nullable=False),
        sa.Column("asset_class", sa.String(), nullable=False),
        sa.Column("sector", sa.String(), nullable=False),
        sa.Column("coverage_symbol", sa.String(), nullable=False),
        sa.Column("analyst_id", sa.Uuid(), nullable=False),
        sa.Column("publication_date", sa.Date(), nullable=False),
        sa.Column("audience", sa.String(), nullable=False),
        sa.Column("rating", sa.String(), nullable=False),
        sa.Column("target_price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("embargo_until", sa.Date(), nullable=False),
        sa.Column("client_access_tier", sa.String(), nullable=False),
        sa.Column("summary", sa.String(), nullable=False),
        sa.Column("internal_draft_notes", sa.String(), nullable=True),
        sa.Column("source_model", sa.String(), nullable=False),
        sa.Column("watermark", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("org_id", "research_id"),
    )
    op.create_index(
        "ix_bank_research_org_id_coverage_symbol",
        "bank_research",
        ["org_id", "coverage_symbol"],
        unique=False,
    )
    op.create_table(
        "bank_trades",
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("trade_id", sa.String(), nullable=False),
        sa.Column("client_id", sa.String(), nullable=False),
        sa.Column("account_id", sa.String(), nullable=False),
        sa.Column("desk", sa.String(), nullable=False),
        sa.Column("asset_class", sa.String(), nullable=False),
        sa.Column("instrument", sa.String(), nullable=False),
        sa.Column("side", sa.String(), nullable=False),
        sa.Column("quantity", sa.BigInteger(), nullable=False),
        sa.Column("price", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("notional_usd", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column("trade_timestamp", sa.DateTime(), nullable=False),
        sa.Column("settlement_date", sa.Date(), nullable=False),
        sa.Column("trader_id", sa.Uuid(), nullable=False),
        sa.Column("venue", sa.String(), nullable=False),
        sa.Column("pnl_usd", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("var_1d_usd", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("strategy", sa.String(), nullable=False),
        sa.Column("counterparty", sa.String(), nullable=False),
        sa.Column("internal_comment", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("org_id", "trade_id"),
    )
    op.create_index(
        "ix_bank_trades_org_id_account_id",
        "bank_trades",
        ["org_id", "account_id"],
        unique=False,
    )
    op.create_index(
        "ix_bank_trades_org_id_client_id",
        "bank_trades",
        ["org_id", "client_id"],
        unique=False,
    )
    op.create_table(
        "bank_transactions",
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("transaction_id", sa.String(), nullable=False),
        sa.Column("client_id", sa.String(), nullable=False),
        sa.Column("account_id", sa.String(), nullable=False),
        sa.Column("transaction_type", sa.String(), nullable=False),
        sa.Column("amount_usd", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("origin_country", sa.String(), nullable=False),
        sa.Column("destination_country", sa.String(), nullable=False),
        sa.Column("beneficiary_name", sa.String(), nullable=False),
        sa.Column("beneficiary_account", sa.String(), nullable=False),
        sa.Column("purpose", sa.String(), nullable=False),
        sa.Column("channel", sa.String(), nullable=False),
        sa.Column("aml_risk_score", sa.Integer(), nullable=False),
        sa.Column("fraud_score", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("alert_id", sa.String(), nullable=True),
        sa.Column("investigation_notes", sa.String(), nullable=True),
        sa.Column("source_system", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("org_id", "transaction_id"),
    )
    op.create_index(
        "ix_bank_transactions_org_id_account_id",
        "bank_transactions",
        ["org_id", "account_id"],
        unique=False,
    )
    op.create_index(
        "ix_bank_transactions_org_id_client_id",
        "bank_transactions",
        ["org_id", "client_id"],
        unique=False,
    )
    op.add_column(
        "organizations",
        sa.Column(
            "sandbox", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.add_column(
        "organizations",
        sa.Column("sandbox_key_hash", sa.String(length=64), nullable=True),
    )
    op.create_index(
        op.f("ix_organizations_sandbox_key_hash"),
        "organizations",
        ["sandbox_key_hash"],
        unique=True,
    )
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_unique_constraint("users_org_id_email_key", "users", ["org_id", "email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_org_id_email_key", "users", type_="unique")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.drop_index(op.f("ix_organizations_sandbox_key_hash"), table_name="organizations")
    op.drop_column("organizations", "sandbox_key_hash")
    op.drop_column("organizations", "sandbox")
    op.drop_index(
        "ix_bank_transactions_org_id_client_id", table_name="bank_transactions"
    )
    op.drop_index(
        "ix_bank_transactions_org_id_account_id", table_name="bank_transactions"
    )
    op.drop_table("bank_transactions")
    op.drop_index("ix_bank_trades_org_id_client_id", table_name="bank_trades")
    op.drop_index("ix_bank_trades_org_id_account_id", table_name="bank_trades")
    op.drop_table("bank_trades")
    op.drop_index("ix_bank_research_org_id_coverage_symbol", table_name="bank_research")
    op.drop_table("bank_research")
    op.drop_table("bank_identity_profiles")
    op.drop_table("bank_data_catalog")
    op.drop_index("ix_bank_clients_org_id_client_name", table_name="bank_clients")
    op.drop_table("bank_clients")
    op.drop_index("ix_bank_accounts_org_id_client_id", table_name="bank_accounts")
    op.drop_table("bank_accounts")
    # ### end Alembic commands ###
