"""add the user to events, mcp servers and policies

Revision ID: 4aa089bcb498
Revises: 92a37152c48b
Create Date: 2026-10-03 16:15:40.142992

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4aa089bcb498"
down_revision: str | Sequence[str] | None = "92a37152c48b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("control_events", sa.Column("user_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_control_events_user_id"), "control_events", ["user_id"], unique=False
    )
    op.create_foreign_key(
        "control_events_user_id_fkey", "control_events", "users", ["user_id"], ["id"]
    )
    op.add_column("mcp_servers", sa.Column("created_by_id", sa.Uuid(), nullable=True))
    op.add_column("mcp_servers", sa.Column("updated_by_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        "mcp_servers_updated_by_id_fkey",
        "mcp_servers",
        "users",
        ["updated_by_id"],
        ["id"],
    )
    op.create_foreign_key(
        "mcp_servers_created_by_id_fkey",
        "mcp_servers",
        "users",
        ["created_by_id"],
        ["id"],
    )
    op.add_column("policies", sa.Column("updated_by_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        "policies_updated_by_id_fkey", "policies", "users", ["updated_by_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("policies_updated_by_id_fkey", "policies", type_="foreignkey")
    op.drop_column("policies", "updated_by_id")
    op.drop_constraint(
        "mcp_servers_created_by_id_fkey", "mcp_servers", type_="foreignkey"
    )
    op.drop_constraint(
        "mcp_servers_updated_by_id_fkey", "mcp_servers", type_="foreignkey"
    )
    op.drop_column("mcp_servers", "updated_by_id")
    op.drop_column("mcp_servers", "created_by_id")
    op.drop_constraint(
        "control_events_user_id_fkey", "control_events", type_="foreignkey"
    )
    op.drop_index(op.f("ix_control_events_user_id"), table_name="control_events")
    op.drop_column("control_events", "user_id")
    # ### end Alembic commands ###
