"""add organizations

Revision ID: f7047220f77a
Revises: 4aa089bcb498
Create Date: 2026-10-03 19:15:36.588197

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f7047220f77a"
down_revision: str | Sequence[str] | None = "4aa089bcb498"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "role_policies",
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=255), nullable=False),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name="role_policies_org_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"], ["users.id"], name="role_policies_updated_by_id_fkey"
        ),
        sa.PrimaryKeyConstraint("org_id", "role"),
    )
    op.drop_table("policies")
    op.add_column("control_events", sa.Column("org_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_control_events_org_id"), "control_events", ["org_id"], unique=False
    )
    op.create_foreign_key(
        "control_events_org_id_fkey",
        "control_events",
        "organizations",
        ["org_id"],
        ["id"],
    )
    op.add_column("mcp_servers", sa.Column("org_id", sa.Uuid(), nullable=True))
    op.drop_constraint(op.f("mcp_servers_name_key"), "mcp_servers", type_="unique")
    op.create_index(
        op.f("ix_mcp_servers_org_id"), "mcp_servers", ["org_id"], unique=False
    )
    op.create_unique_constraint(
        "mcp_servers_org_id_name_key", "mcp_servers", ["org_id", "name"]
    )
    op.create_foreign_key(
        "mcp_servers_org_id_fkey", "mcp_servers", "organizations", ["org_id"], ["id"]
    )
    op.add_column("users", sa.Column("org_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_users_org_id"), "users", ["org_id"], unique=False)
    op.create_foreign_key(
        "users_org_id_fkey", "users", "organizations", ["org_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_org_id_fkey", "users", type_="foreignkey")
    op.drop_index(op.f("ix_users_org_id"), table_name="users")
    op.drop_column("users", "org_id")
    op.drop_constraint("mcp_servers_org_id_fkey", "mcp_servers", type_="foreignkey")
    op.drop_constraint("mcp_servers_org_id_name_key", "mcp_servers", type_="unique")
    op.drop_index(op.f("ix_mcp_servers_org_id"), table_name="mcp_servers")
    op.create_unique_constraint(
        op.f("mcp_servers_name_key"),
        "mcp_servers",
        ["name"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("mcp_servers", "org_id")
    op.drop_constraint(
        "control_events_org_id_fkey", "control_events", type_="foreignkey"
    )
    op.drop_index(op.f("ix_control_events_org_id"), table_name="control_events")
    op.drop_column("control_events", "org_id")
    op.create_table(
        "policies",
        sa.Column("role", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column(
            "settings",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("updated_by_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["updated_by_id"], ["users.id"], name=op.f("policies_updated_by_id_fkey")
        ),
        sa.PrimaryKeyConstraint("role", name=op.f("policies_pkey")),
    )
    op.drop_table("role_policies")
    op.drop_table("organizations")
    # ### end Alembic commands ###
