"""add control events table

Revision ID: d9468defef33
Revises: cbcb85758011
Create Date: 2026-10-03 13:15:52.922934

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d9468defef33"
down_revision: str | Sequence[str] | None = "cbcb85758011"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "control_events",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("event", sa.String(length=32), nullable=False),
        sa.Column("action", sa.String(length=16), nullable=True),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_control_events_created_at"),
        "control_events",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_control_events_trace_id"), "control_events", ["trace_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_control_events_trace_id"), table_name="control_events")
    op.drop_index(op.f("ix_control_events_created_at"), table_name="control_events")
    op.drop_table("control_events")
    # ### end Alembic commands ###
